#!/usr/bin/env python3
"""Live drums stem visualizer with pre-computed solenoid triggers.

Plays the drums stem while showing a real-time scrolling plot of
RMS energy, LED brightness, and solenoid fire events loaded from
``solenoid_hits.json`` (generated by ``solenoid_precompute.py``).

Usage:
    python drums_visualizer.py --song 04_DieYoung
    python drums_visualizer.py --song 04_DieYoung --no-solenoid
    python drums_visualizer.py --song 04_DieYoung --window 15 --offset -0.02
"""

import argparse
import collections
import colorsys
import json
import random
import threading
import time
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("macosx")
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
import sounddevice as sd
import soundfile as sf

from config import (
    BLOCK_SIZE,
    DEFAULT_BAUD_RATE,
    SAMPLE_RATE,
    get_serial_port,
    get_stems_dir,
)
from knob_mixer import BeatDetector, KnobReader, _resample, led_pairs_command

PLOT_FPS = 30


def load_drums(song_name: str, stems_dir: Path) -> np.ndarray:
    stem_path = stems_dir / "htdemucs" / song_name / "drums.wav"
    if not stem_path.is_file():
        raise FileNotFoundError(f"Missing drums stem: {stem_path}")
    data, sr = sf.read(stem_path, dtype="float32")
    if data.ndim == 1:
        data = np.column_stack([data, data])
    if sr != SAMPLE_RATE:
        data = _resample(data, sr, SAMPLE_RATE)
    peak = np.max(np.abs(data))
    if peak > 0:
        data *= 0.9 / peak
    return data


def load_hit_times(song_name: str, stems_dir: Path, offset_s: float = 0.0) -> list[float]:
    hit_path = stems_dir / "htdemucs" / song_name / "solenoid_hits.json"
    if not hit_path.is_file():
        raise FileNotFoundError(
            f"Missing {hit_path}\n"
            f"Run:  python solenoid_precompute.py --song {song_name}"
        )
    payload = json.loads(hit_path.read_text())
    hits = payload["hits"]
    if offset_s:
        hits = [max(0.0, t + offset_s) for t in hits]
    return hits


def main() -> None:
    parser = argparse.ArgumentParser(description="Live drums visualizer + solenoid triggers")
    parser.add_argument("--song", type=str, required=True,
                        help="Song stem name under stems/htdemucs")
    parser.add_argument("--no-solenoid", action="store_true",
                        help="Disable solenoid pulses and Arduino LED output")
    parser.add_argument("--window", type=float, default=10.0,
                        help="Visible time window in seconds (default: 10)")
    parser.add_argument("--offset", type=float, default=0.0,
                        help="Extra time offset in seconds for hits (negative = earlier)")
    args = parser.parse_args()

    stems_dir = get_stems_dir()
    drums = load_drums(args.song, stems_dir)
    hit_times = load_hit_times(args.song, stems_dir, offset_s=args.offset)
    duration = len(drums) / SAMPLE_RATE
    print(f"Loaded drums stem: {args.song}  ({duration:.1f}s)")
    print(f"Loaded {len(hit_times)} pre-computed solenoid hits")

    window_sec = args.window
    blocks_per_sec = SAMPLE_RATE / BLOCK_SIZE
    history_len = int(window_sec * blocks_per_sec) + 1

    # -- shared state --
    rms_history = collections.deque([0.0] * history_len, maxlen=history_len)
    brightness_history = collections.deque([0.0] * history_len, maxlen=history_len)
    lock = threading.Lock()

    beat = BeatDetector()
    frame_pos = [0]
    playback_time = [0.0]
    hit_index = [0]
    pending_hits = [0]
    fired_times: list[float] = []
    flash_count = [0]
    prev_brightness = [0.0]

    use_solenoid = not args.no_solenoid
    knob: Optional[KnobReader] = None
    if use_solenoid:
        try:
            port = get_serial_port()
            knob = KnobReader(port, DEFAULT_BAUD_RATE)
            knob.start()
            print(f"Arduino on {port} — solenoid enabled")
        except RuntimeError as e:
            print(f"Warning: {e}\n  Running without solenoid hardware.")
            use_solenoid = False

    def audio_callback(outdata: np.ndarray, frames: int,
                       _time_info: object, status: sd.CallbackFlags) -> None:
        if status:
            print(f"  audio: {status}", flush=True)

        pos = frame_pos[0]
        data_len = len(drums)
        end = pos + frames
        if end <= data_len:
            chunk = drums[pos:end]
        else:
            chunk = np.concatenate([drums[pos:], drums[:end - data_len]])
        frame_pos[0] = end % data_len
        outdata[:] = chunk

        rms = float(np.sqrt(np.mean(chunk * chunk)))
        t_start = pos / SAMPLE_RATE
        t_end = end / SAMPLE_RATE
        brightness = beat.update(rms)

        if brightness > 0.55 and brightness > prev_brightness[0]:
            flash_count[0] += 1
        prev_brightness[0] = brightness

        idx = hit_index[0]
        fires = 0
        while idx < len(hit_times) and hit_times[idx] < t_end:
            if hit_times[idx] >= t_start:
                fires += 1
                fired_times.append(hit_times[idx])
            idx += 1

        with lock:
            rms_history.append(rms)
            brightness_history.append(brightness)
            playback_time[0] = t_end
            hit_index[0] = idx
            if fires:
                pending_hits[0] += fires

    PARTY_HUES = [
        0.83, 0.75, 0.92, 0.0, 0.97, 0.66, 0.58, 0.05,
    ]

    def party_color() -> tuple[int, int, int]:
        hue = random.choice(PARTY_HUES) + random.uniform(-0.03, 0.03)
        sat = random.uniform(0.8, 1.0)
        val = random.uniform(0.4, 0.55)
        r, g, b = colorsys.hsv_to_rgb(hue % 1.0, sat, val)
        return (int(r * 255), int(g * 255), int(b * 255))

    def party_palette() -> list[tuple[int, int, int]]:
        return [party_color() for _ in range(4)]

    led_colors = party_palette()
    last_flash_count = [0]

    # -- build the figure --
    fig, (ax_rms, ax_bright) = plt.subplots(
        2, 1, figsize=(14, 6), sharex=True,
        gridspec_kw={"height_ratios": [2.5, 1], "hspace": 0.05},
    )
    fig.patch.set_facecolor("#0e0e0e")
    fig.canvas.manager.set_window_title(f"Drums — {args.song}")

    for ax in (ax_rms, ax_bright):
        ax.set_facecolor("#141414")
        ax.tick_params(colors="#888", labelsize=8)
        for spine in ax.spines.values():
            spine.set_color("#333")

    default_hex = f"#{led_colors[0][0]:02x}{led_colors[0][1]:02x}{led_colors[0][2]:02x}"
    line_rms, = ax_rms.plot([], [], color=default_hex, linewidth=0.8, alpha=0.9)
    fill_rms = ax_rms.fill_between([0], [0], color=default_hex, alpha=0.25)
    line_bright, = ax_bright.plot([], [], color=default_hex, linewidth=0.8, alpha=0.9)
    fill_bright = ax_bright.fill_between([0], [0], color=default_hex, alpha=0.25)
    solenoid_artists: list = []

    ax_rms.set_ylabel("RMS Energy", color="#aaa", fontsize=9)
    ax_rms.set_title(f"Live Drums — {args.song}  (pre-computed hits)", color="#eee",
                     fontsize=12, pad=8)
    ax_bright.set_ylabel("Brightness", color="#aaa", fontsize=9)
    ax_bright.set_xlabel("Time (s)", color="#aaa", fontsize=9)
    ax_bright.set_ylim(-0.02, 1.05)

    hit_text = ax_rms.text(0.99, 0.95, "", transform=ax_rms.transAxes,
                           ha="right", va="top", fontsize=10, color="#ef5350",
                           fontweight="bold")

    # draw faint markers for ALL pre-computed hits as a timeline preview
    for ht in hit_times:
        ax_rms.axvline(ht, color="#ef5350", alpha=0.04, linewidth=0.5)

    def update(_frame: int):
        nonlocal fill_rms, fill_bright

        with lock:
            rms_arr = np.array(rms_history)
            bright_arr = np.array(brightness_history)
            t_now = playback_time[0]
            n_fires = len(fired_times)
            queued = pending_hits[0]

        t_start = max(0.0, t_now - window_sec)
        t_end = t_now
        t_axis = np.linspace(t_start, t_end, len(rms_arr))

        fc = flash_count[0]
        if fc != last_flash_count[0]:
            led_colors[:] = party_palette()
            last_flash_count[0] = fc

        c = led_colors[0]
        hex_c = f"#{c[0]:02x}{c[1]:02x}{c[2]:02x}"

        line_rms.set_data(t_axis, rms_arr)
        line_rms.set_color(hex_c)
        line_bright.set_data(t_axis, bright_arr)
        line_bright.set_color(hex_c)

        fill_rms.remove()
        fill_rms = ax_rms.fill_between(t_axis, rms_arr, color=hex_c, alpha=0.25)
        fill_bright.remove()
        fill_bright = ax_bright.fill_between(t_axis, bright_arr, color=hex_c, alpha=0.25)

        ax_rms.set_xlim(t_start, t_end)
        rms_peak = max(rms_arr.max() * 1.3, 0.01)
        ax_rms.set_ylim(-rms_peak * 0.03, rms_peak)

        for a in solenoid_artists:
            a.remove()
        solenoid_artists.clear()

        recent_fires = [ft for ft in fired_times if ft > t_start]
        for ft in recent_fires:
            age = t_now - ft
            alpha = max(0.2, 1.0 - age / 0.4)
            ln = ax_rms.axvline(ft, color=hex_c, alpha=alpha, linewidth=1.5)
            solenoid_artists.append(ln)
            ln2 = ax_bright.axvline(ft, color=hex_c, alpha=alpha * 0.6, linewidth=1.0)
            solenoid_artists.append(ln2)

        hit_text.set_text(f"SOLENOID  {n_fires}/{len(hit_times)}" if n_fires else "")

        if knob:
            b = bright_arr[-1] if len(bright_arr) else 0.0
            knob.send(led_pairs_command(led_colors, brightness=b))
            with lock:
                hits = pending_hits[0]
                pending_hits[0] = 0
            for _ in range(hits):
                knob.send("S")

        return (line_rms, line_bright, fill_rms, fill_bright, hit_text)

    print("Starting live visualizer — close the window or Ctrl+C to stop.\n")
    try:
        stream = sd.OutputStream(
            samplerate=SAMPLE_RATE,
            channels=2,
            dtype="float32",
            blocksize=BLOCK_SIZE,
            callback=audio_callback,
        )
        stream.start()
        ani = animation.FuncAnimation(
            fig, update, interval=1000 // PLOT_FPS, blit=False, cache_frame_data=False,
        )
        plt.show()
    except KeyboardInterrupt:
        print("\nStopping...")
    finally:
        if "stream" in dir():
            stream.stop()
            stream.close()
        if knob:
            knob.stop()


if __name__ == "__main__":
    main()
